const {
	PORT = 3000,
	NODE_ENV,
	JWT_TOKEN,
	WEB_PUSH_PUBLIC_KEY,
	WEB_PUSH_PRIVATE_KEY,
	FIREBASE_TYPE,
	FIREBASE_PROJECT_ID,
	FIREBASE_PRIVATE_KEY_ID,
	FIREBASE_PRIVATE_KEY,
	FIREBASE_CLIENT_EMAIL,
	FIREBASE_CLIENT_ID,
	FIREBASE_AUTH_URL,
	FIREBASE_TOKEN_URL,
	FIREBASE_AUTH_PROVIDER,
	FIREBASE_CLIENT,
	FIREBASE_UNIVERSE_DOMAIN
} = process.env

module.exports = {
	PORT,
	NODE_ENV,
	JWT_TOKEN,
	WEB_PUSH_PUBLIC_KEY,
	WEB_PUSH_PRIVATE_KEY,
	FIREBASE_TYPE,
	FIREBASE_PROJECT_ID,
	FIREBASE_PRIVATE_KEY_ID,
	FIREBASE_PRIVATE_KEY,
	FIREBASE_CLIENT_EMAIL,
	FIREBASE_CLIENT_ID,
	FIREBASE_AUTH_URL,
	FIREBASE_TOKEN_URL,
	FIREBASE_AUTH_PROVIDER,
	FIREBASE_CLIENT,
	FIREBASE_UNIVERSE_DOMAIN
}
